### ISSUE TITLE
mineways.com: site is not secure

### ISSUE THREAD

**Issue by DWolf-19** [erich666/Mineways#123]
I can't access site using secure https (https://mineways.com/). But I found another domain in README (https://www.realtimerendering.com/) that supports a secure connection.

Why is repository and README header showing an outdated link with `http`? Why not insert https://www.realtimerendering.com/ everywhere if this is the official site? Or am I missing something.

**Comment by erich666** [comment]
Good point, and I noticed this problem starting just this last week. It's annoying, and I don't know how to fix it for anyone else using "mineways.com" (other than starting a new hosted website using the URL, vs. a redirect). Redirection has worked for 12 years; now something's changed (not by me) and redirection is failing.

If you have any ideas or theories, let me know. I coined and registered mineways.com because it's way more memorable than https://www.realtimerendering.com/erich/minecraft/public/mineways

**Comment by erich666** [comment]
Anyway, I've fixed the internal links on my own webpages for the site to directly call the longer URL, so at least that's OK. I'll need to make a number of other fixes here and there (e.g., in the code itself), so am leaving this bug open.

**Comment by erich666** [comment]
Cleaned out the direct "mineways.com" links in my own documentation now, though I still find the shortener useful.
