### ISSUE TITLE
Jump to player doesn't match in the nether

### ISSUE THREAD

**Issue by zNightlord** [erich666/Mineways#129]
The jump to player command nether dimension coordinate scale divided by 8 doesn't seem to be match anymore? 

> How to reproduce:
> Create a new world
> Go to the nether, load it and save
> Open, loads in Mineways
> Use Jump to player command

**Comment by erich666** [comment]
Thanks, I'll give it a look.

**Comment by erich666** [comment]
OK, this will be fixed when I release 12.03. I'm not going to release a new version just for this bug (I figure there will be other bugs reported sometime soon), but I've made a beta with this fix here: https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/Mineways_beta_12.03.zip - give it a try and see if it works for you.

I decided against making the code so that if you jump to the player and the player is in the nether, it also switches to the nether. But, this was a bit more work than I wanted to do, with side effects (like turning on "hide obscured"), and might be unexpected when done. It was tempting to give a warning if the player was in hell and you were viewing the overworld, but this warning could be annoying as it would be repeated each time you jumped to the player's location, so I didn't add one. I figure the user will (mostly) figure out what's happening.
