### ISSUE TITLE
More materials, please (was: Rails no longer cary the active/inactive tag)

### ISSUE THREAD

**Issue by JMY1000** [erich666/Mineways#16]
Since they've been combined into the same material, it makes it nearly impossible for scripts like CyclesMineways to distinguish between the active and inactive versions and properly assign the correct shader (light emitting vs. not light emitting) It'd be nice to get this tag back.

**Comment by erich666** [comment]
I'm confused - were these ever different before, in a previous version of Mineways? Active and inactive powered rails both use the same block ID, #27. 

Oh, I think what you're saying with "Since" is actually "Because", i.e., "Because they are combined into" - the "Since" threw me off, as in "Since version 5.00 rails have been combined...". Anyway, yes, I'll put "finely divided materials" as a possible future option in Mineways. The messy part is that I don't want to divide *everything* by their data values, but rather want to sometimes divide always (say, wool or stained clay), sometimes divide a little (powered vs. unpowered, a single bit in the data field), and sometimes not divide at all (different stair orientations, torch orientations, etc.). The tricky bit is figuring how to best represent these three different states.

Idea: perhaps a bit field, e.g. 0x8 for rails, 0xf for wool (all bits matter), 0x0 for torches (don't care). Hopefully this covers all the possibilities, that there's not some goofy block that says for data 0-5 that's one type, 6-7 is another, 8-10 a third, 11 a fourth, etc.

**Comment by JMY1000** [comment]
I'm not too familiar with how data is stored within the OBJs, so as long as there's some way it's accessible once imported into Blender, everything's fine. Knowing anything that doesn't effect shading isn't needed.

I'm not 100% sure weather they were treated as a different block once exported, but there was code in CyclesMineways that seems to point to them being separate at some point (though it's possible this was just improperly written.)

**Comment by ThomasLynn** [comment]
I think the best way for Mineways to communicate data to CyclesMineways is through the names. If you want, say to add all the wool types, name them "wool_0", "wool_1", "wool_2".

For coding this on python's end, we can use something like this:
>>> a=["wood","grass","stone"]
>>> a.extend(["wool_"+str(i) for i in [1,2,3]])
>>> a
['wood', 'grass', 'stone', 'wool_1', 'wool_2', 'wool_3']

As for active and inactive blocks, the method you're currently using ((active) and (inactive)) works great.

**Comment by JMY1000** [comment]
@ThomasLynn Do we need that metadata to be conveyed? In addition, that's single dimensional: for things that can carry 2+ NBT tags in Minecraft, this system doesn't work too well.

**Comment by erich666** [comment]
Ah, right, adding a data suffix is a good plan. I'll mull it over. I'm going on vacation for three weeks come this Friday, so I'll have a lot of mulling time.

**Comment by ThomasLynn** [comment]
@JMY1000 I've just realised, this is also the **only** way of doing it. If you want to apply a different node tree to, say, an on or off comparator, it needs to be two separate objects in Blender, or they'll only apply one node tree to both (as Blender can't tell them apart)

I've just gone onto the minecraft test world, and have been looking over the blocks that might use 2+  dimensions of data, and I'd say redstone is the worst offender.
redstone can be:
on or off
connected north, connected north + up one block, not connected north
connected south, connected north + up one block, not connected south
connected east, connected north + up one block, not connected east
connected west, connected north + up one block, not connected west
for (I think) a grand total of 162 possible blocks of redstone.

if you wanted to apply a different texture to  each one, they'd have to be different objects. Do note: even in worlds that use a lot of redstone, they are unlikely to use all 162 possibilities.

So, I'd say there's two ways of going about this.

1) you just use (active) and (inactive) tags at the end of names, like you've been doing. There's not much point in having blocks with the same texture/node tree separated anyway

2) you use some kind of basic encoding in your block names
for redstone, it would be "redstone_[north][east][south][west][active]"
[north], [east], [south], and [west] are values between 0 and 2, 0 for disconnected, 1 for connect at the same level, and 2 is for connected at a higher level
[active] is either a (for active) or i (for inactive)
for example: 
redstone_2110a.
would be a redstone wire connected to another redstone wire that is higher to the north, a redstone wire at the same elevation to the east and south, is not connected to the west, and is active.

Using this system you have have different node trees for different redstone blocks, or plant pots, or stairs (as stairs can have corner blocks, there's a lot of them). You could also pick and choose which blocks you think this would be useful.

**Comment by erich666** [comment]
I don't think there are 162 variants: each face is a separate tile, so "up one block" doesn't factor in. Each tile itself has just one level of power (0-16), one color.

Right now in Mineways redstone is on or off (it used to always just be on, so this is progress). I'm probably not going to ever mess with this, because (as you point out) it leads to a huge number of variants in color and shape. Each variant creates a new texture tile in the texture map, and there's only so much room in the map (I put an upper limit on the map size as possible, as the various 64x64 tile textures out there will give a huge map if I let the texture size grown without limits). Mineways also simply deals with rotations of a pattern by rotating it, e.g. a 3-connection tile is reused and rotated to the 4 positions possible, so cutting down the number of texture tiles needed.

Whatever the case, in Mineways at most I'd make two materials for these: powered (a little or a lot) and not powered. Though, hmmm, that's an idea: output the redstone material by power level. If someone then wants to deal with each power level precisely, they can.

**Comment by ThomasLynn** [comment]
Yes, having redstone's meta data (0 to 15 power level) would be really useful for us. Naming them redstone_0, redstone_1, ... , redstone_15 would be great, then we can apply an emission strength with code like
`
emission_strength = int(name[name.rfind("_")+1:])
`

**Comment by erich666** [comment]
OK, good deal, duly noted. That said, time to pack for my vacation :+1: - this won't happen for a bit, though maybe I'll sneak it in just before Minecon.

**Comment by ThomasLynn** [comment]
Sounds good.

**Comment by erich666** [comment]
I should note that with redstone Mineways itself is going to output "on" and "off" and that's it, as far as its textures are concerned. If each tile had its own level 0-15 for the intensity of the redstone, the number of textures output would get unreasonably high (or at least more than I normally want to deal with - could be hundreds of combinations, as there's 0-15 times pattern times background tile). I'll look into output of separate materials for each redstone level, though. All that said, I'm kinda running out of time for working on Mineways for awhile - I need to work on a new edition of [Real-Time Rendering](http://realtimerendering.com).

**Comment by erich666** [comment]
Done! In [version 5.04](https://github.com/erich666/Mineways/releases/tag/5.04). Read about it [here](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#material_subtypes).

It was a giant pain to go through all the 230+ blocks and figure out which are separate materials and which are not. Some I was undecided about, so can be swayed one way or the other. Let me know. But, I'm glad I did go through all the blocks, as I found a few inaccuracies and fixed those up along the way.

**Comment by ThomasLynn** [comment]
As expected, this change resets quite a lot of blocks back to the default solid shader. It took me a little while finding the new options, I'll make a new issue thread about it, though as it's off-topic in this one.

Thanks for implementing this, though!

**Comment by erich666** [comment]
Ah, right, that it would indeed do for Cycles, which clearly needs to change if it wants to support this feature.

**Comment by JMY1000** [comment]
I've opened an issue on my repo for it, but it unfortunately could be a while before I can fix it.
