### ISSUE TITLE
How to select fixed rect or chunk?

### ISSUE THREAD

**Issue by acterhd** [erich666/Mineways#19]
Hello. How I can select fixed size region?

**Comment by JMY1000** [comment]
Right click and drag.

**Comment by acterhd** [comment]
I tried, but very problematic select 16x16 and precise.

**Comment by JMY1000** [comment]
You can zoom using the scroll wheel, but I'm not sure if there's more you can do.

**Comment by acterhd** [comment]
But I want select non standard, for example 256x256.

**Comment by erich666** [comment]
If you don't like clicking and dragging, there are two options:

1) If you know your exact coordinates, simply type them in. See [this image](http://www.realtimerendering.com/erich/minecraft/public/mineways/images/export_dialog.jpg). In the upper left are the six coordinates that define the box that gets exported.

2) If you have a selection area you want to select again and again, or otherwise want to automate the process, use the [scripting system](http://www.realtimerendering.com/erich/minecraft/public/mineways/scripting.html). For example, you'd put this line of text:

> Selection location: 60, 0, 60 to 80, 255, 100

in some file named "my_selection.mwscript" or whatever you like, and then use File | Import Settings and read in this text file. It will select the area you want.
