### ISSUE TITLE
Mineways cannot read 1.12 World

### ISSUE THREAD

**Issue by frogocomics** [erich666/Mineways#31]
Says it cannot read the world. It is openable on Jmc2Obj and MCEdit.
[Level.dat.zip](https://github.com/erich666/Mineways/files/1206438/Level.dat.zip)

**Comment by erich666** [comment]
That level.dat file reads fine in the latest Mineways. What *exactly* is the error message? And, are you on Windows 10 or something else?

I'll bet dollars to donuts it's a path or folder name problem, but I have not been able to reproduce the problem here and so cannot fix it. I've tried all sorts of strange things for the paths and directory names, but everything works fine here. So, I'd love _any_ hints as to what it could be. One thing to try: unzip mineways.zip into c:\temp\mineways (say) and try running it from there. Next thing to try: copy the world directory to, say, c:\temp and use File -> Open... to select the level.dat and open the world manually.

Avoid complex paths, avoid paths with umlauts or punctuation or spaces in them. Keep it simple. Does any of this help make Mineways work? If I can isolate the problem, I can fix it, but without more info I'm out of luck.

**Comment by erich666** [comment]
One other idea: if the computer is not set to a locale of US English, try switching it to that. A drastic measure, but I don't have any great ideas at this point. I also have made a Mineways beta that has more diagnostics output.  Email me to have me send you a copy.

**Comment by frogocomics** [comment]
My locale is English. Error message is "Cannot read world"

**Comment by frogocomics** [comment]
When I open it in the "Open World": I says "cannot read file verison"

**Comment by frogocomics** [comment]
It does not work for any other world.

**Comment by erich666** [comment]
Did you try the diagnostics version I sent you? This version gives more information, such as path and a "sub error code".

**Comment by frogocomics** [comment]
I sent you an email. Didn't get reply

**Comment by erich666** [comment]
I emailed you and attached a file - I suspect it's in your spam folder. I've just tried emailing again.

**Comment by frogocomics** [comment]
Open World: http://prntscr.com/g62cp3
Open: http://prntscr.com/g62cyo
Perhaps it has to do with the slashes? (/)

In different directory: 
http://prntscr.com/g62dnd

**Comment by erich666** [comment]
I agree that the separator could be messing things up, so I went through the (fairly painful) process of changing the separator. New version emailed to you. Please do send me the sub-error code that gets shown in the dialog when you try to load a world and it fails (at least, I hope it shows this code). If it's a positive number, this corresponds to the constant in the table here: https://msdn.microsoft.com/en-us/library/t3ayayh1(v=vs.120).aspx

**Comment by frogocomics** [comment]
http://prntscr.com/g64872
Does this for every world.
http://prntscr.com/g648ip
When you open the world.

**Comment by erich666** [comment]
Thanks for your help, and now I'm truly baffled, as the error is:

EMFILE | Too many open files | 24

if I read the runes aright. So, no idea, sorry.

One last thing: using the original Mineways distribution, try running the "mineways_without_worlds.bat" file (i.e., double-click it). This starts up Mineways without looking at your Minecraft world saves directory. Sometimes corrupt or incomplete world data can cause Mineways problems. You could then try opening a world manually (which I expect won't work for some reason...). If Mineways is still not working, please run "mineways_debug_log.bat" and look at or send me the resulting mineways_exec.log file, which may give some hint as to what's going on.

**Comment by frogocomics** [comment]
World: http://www.mediafire.com/file/0wumyzvxxj92f55/World_Problem.zip
Debug Log: https://pastebin.com/ARfuhhAL

**Comment by erich666** [comment]
I downloaded your world aaaa, opened it just fine, exported fine, displayed the file. Like I say, everything works on this end, on Windows 10. You might consider trying Mineways on another machine and see how it goes.

One more thing to try, that would help me see what is going on with your machine: make a text file called "mineways_min_debug.bat" (or whatever you want to call it) and make it have just one line in the file:
`mineways.exe -l mineways_exec.log -s C:\`

Save this file to where mineways.exe (diagnostic or not) is located. Double-click to run. Now try "File -> Open..." and select a level.dat file for some world. I'd pick "Canyon Test" since that's a 1.10.2 world. It should open, but probably won't. Quit Mineways. I definitely want to see the error message and the debug log.

Why do this? The log you sent shows that it can (at least briefly) open all your worlds, and it detects some are pre-1.9. It seems to find 128 worlds and then all the rest don't appear to get looked at - hmmm, that's suspicious that it stops at that point. Digging a bit, this seems to be a flaw with gzdopen (zlib) in some way: Mineways hits a world limit that it can open. The worlds are supposed to then be closed, but something is hanging on to them. I've tracked through the code as best I can, but I don't see anything I'm doing wrong - it may be a bug in zlib itself. I suspect I need to update to a newer version of zlib, which will no doubt be a total pain to do. Note to self: https://zlib.net/ Or maybe it's something else entirely... Anyway, I can at least issue a warning for this problem, and probably avoid some pain by allowing "only" 50 worlds to load.

However, if you open using mineways_min_debug.bat, this "running out of worlds" problem should not be visible, and you'll generate a debug log file.

So why you can't open a world is still a mystery, but I'm hoping your clues will help me figure it out.

Sorry for all this, but it's a huge help to have someone running these tests on their machine that is having problems. If I could reproduce the problem here, I'd be happy, but no such luck yet. You've already uncovered a "file open but not closed" problem, which is good (though mysterious).

**Comment by frogocomics** [comment]
It works.

**Comment by erich666** [comment]
Good! OK, I now know to recommend to people to simply run mineways_without_worlds.bat and open their worlds manually if they run into some sort of problem. I'll work on a fix (or at least a workaround) today.

**Comment by frogocomics** [comment]
Your new version works. If I run it without the batch it works also.

**Comment by erich666** [comment]
Excellent, thanks. One bug down. I hope to get out an official release tonight.

**Comment by erich666** [comment]
Fixed (or at least worked-around) in v5.10: https://github.com/erich666/Mineways/releases/tag/v5.10
