### ISSUE TITLE
World does not import

### ISSUE THREAD

**Issue by frogocomics** [erich666/Mineways#32]
My original world works, but another different world does not work. The level documents are the exact same, but the regions are different. Therefore it must be a problem in the region loading. My world has a large amount of void, so perhaps Mineways has an issue with **completely empty region files**.

See World here (Try looking at it in game, it looks beautiful)
[World Here](http://www.mediafire.com/file/0eztp9xcxsrx416/Another_issue%21.zip)

Opening the worlds (Both in open, and in open world) does not result in an error message, instead it just crashes the software, with a notification from Windows saying the software ran into a problem.

**Comment by erich666** [comment]
This appears to be modded content, not made by Minecraft itself, so all bets are off.

The code that blows up is hit when drawing the map:

    case BLOCK_DOUBLE_FLOWER:
        // subtract 256, one Y level, as we need to look at the bottom of the plant to ID its type.
        dataVal = block->data[(voxel-256)/2];

The value "voxel" is 3, as we are looking at the bottommost level of the block. We look from top to bottom. We should have run into a block above this particular block that was also a double flower (a flower with two blocks). Having a single "top" block of a double flower at level 0, the bottom level, makes no sense. I will guard against this, but it's frankly garbage-in-garbage-out.

**Comment by erich666** [comment]
I've put in the one-line fix and checked it in, but this fix doesn't warrant a new release, since the data's bad. Like it says here: https://minecraft.gamepedia.com/Data_values#Large_Flowers : "Top Half of any Large Plant; low three bits 0x7 are derived from the block below." It's actually not clear to me what the top half of the plant stores, though it does store something. I planted three different double-flowers and the top half was always 0xA, meaning the 8 bit was set and the 2 bit was set (but the flowers were not double-tallgrass). Like I say, modded data. But at least now Mineways won't crash. I'll send you a beta, though I won't bother with a new release.

**Comment by frogocomics** [comment]
I truly appreciate a safeguard. I've been experimenting working with MCRegion terrain higher than 256 blocks, and I created a program to split them into anvil sections. I guess these things are hard to avoid. Thanks. Won't waste any more of your time.

**Comment by erich666** [comment]
I don't mind adding guard code in this case, it's an easy two line fix, but there are _lots_ of ways of breaking Mineways with bad data that it doesn't expect or thinks is impossible. Guarding against all these sorts of cases is hard to test, so I don't bother, since almost all users use unmodded data. If you submit a bug against modded data, please state up front that this is modded data - it saves me time spent thinking it's a bug in Mineways' way of dealing with good data.
