### ISSUE TITLE
[Solved] Grass Block and Grass Render Upside Down

### ISSUE THREAD

**Issue by juniortivotyro** [erich666/Mineways#39]
![issue](https://user-images.githubusercontent.com/8530852/44294305-6debfb80-a252-11e8-804a-30bea6a80160.png)

Using the default settings on mineways, no matter what world I use, this is what happens to textures.

EDIT: Solved - Set OBJ import settings to default and imported.

**Comment by erich666** [comment]
Glad you figured it out. I'm _guessing_ that you use Cinema4D (the report didn't say anything) - did you? If not, let me know which package you used. The [instructions for Cinema4D](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#c4d) warn, in step 4, to use default settings. If this warning is needed for another rendering package, I'd like to know so that I could add it to Mineways' documentation.

**Comment by erich666** [comment]
Closing issue, since no other reports along these lines. Older versions of Cinema 4D have problems with importing OBJ files (files which display in other viewers just fine), [as documented here](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#c4d), Step 0: Make sure you have the latest update of Cinema 4D, at least version R18.057. If you don't, the Mineways file may import to give you a radial pattern for the texture map (I don't know why; it appears to be a bug with Cinema 4D, as such files will display in other applications just fine). Newer versions do not have this problem.
