### ISSUE TITLE
Texture mapping incorrect [Cinema 4D]

### ISSUE THREAD

**Issue by Kappeh** [erich666/Mineways#41]
I haven't tested this in blender but after exporting a model as an obj and importing it into Cinema 4D, I got this result:

![Result](https://i.imgur.com/RaaYOV6.png)

This was using default settings. I have tried many things including exporting without seperating materials, exporting without lesser, detailed textures and different model scales.

I have been able to do this kind of render successfully with older versions of mineways and I can assure you it is not Cinema4D at fault here.

**Comment by erich666** [comment]
Cool example. This problem is noted, twice, on the [front page](http://www.realtimerendering.com/erich/minecraft/public/mineways/). Click on the links to get to [this page](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#c4d) - perform step 0. It's a Cinema 4D problem; you need to get a newer version. I do wish I knew what it was that confuses Cinema 4D, but Mineways export OBJ files display fine in all other applications I've tested.

**Comment by erich666** [comment]
Fixed fully in version 6.08: The problem was that Sketchfab set the OBJ export for rendering to be relative, not absolute, coordinates. For some reason, older versions of Cinema 4D would fail to read these; version R18.057 does not. Fixed by separating Sketchfab export values from the normal rendering export values.
