### ISSUE TITLE
Hоw to export the Survivalcraft world as .obj.

### ISSUE THREAD

**Issue by anatania935** [erich666/Mineways#47]
I unknown export the Survivalcraft world as .obj. 
like Minecraft world open in mineways become as .obj.
can you please make a exporter the Survivalcraft world as .obj.

File type: Survivalcraft World File
Game: https://kaalus.wordpress.com/

**Comment by erich666** [comment]
If I understand you correctly, you're asking for Mineways to support Survivalcraft, which appears to be some modded version of Minecraft, on mobile. Mineways doesn't support mods, mostly because it's a serious, possibly impossible, effort to do so. Even if I added (a lot of) code to support modded block types, there are also rules for many block types: does the new block attach to fences or walls? does it attach to redstone wire? does it affect the level of water? can it be waterlogged? These affect the geometry output, so I haven't tried to support mods in any form - supporting Minecraft in a backward-compatible way is hard enough.

The code is open source, so anyone can modify it as they wish. That said, it's "archaeological code base" after all these years - new features accrete atop older ones, and special cases need special handling, complicating the processing. So, anyone attempting supporting mods will have a heck of a time.

**Comment by anatania935** [comment]
Do you know code and script for survivalcraft world as obj and from 3d models?
![Survivalcraft 2019-09-06 06-20-43](https://user-images.githubusercontent.com/54982785/64431097-936ec180-d06e-11e9-9d76-953c664bc8ac.jpg)
![Survivalcraft 2019-09-06 06-20-56](https://user-images.githubusercontent.com/54982785/64431123-a2ee0a80-d06e-11e9-8cff-49c864145f1d.jpg)

**Comment by erich666** [comment]
I do not; I had never heard of Survivalcraft until you mentioned it.
