### ISSUE TITLE
Faces missing and unnecessary faces

### ISSUE THREAD

**Issue by roket333** [erich666/Mineways#61]
If you have stairs on the north or east of a path block, the back of the stairs will be missing when exported
![image](https://user-images.githubusercontent.com/5241048/84966160-a87c8480-b0c5-11ea-9c5b-47e66e4b4207.png)
On a similar note, the south and west faces of non-solid blocks that should be missing because they're unseen are not culled
![image](https://user-images.githubusercontent.com/5241048/84966169-add9cf00-b0c5-11ea-970e-ea0f13876791.png)

**Comment by erich666** [comment]
Thanks for reporting this, and it turns out to be an easy fix for path blocks; crop blocks had the same problem. I'll put a fix out this weekend.

There are definitely no guarantees for removal of faces between "partial blocks," those that don't fill the block. Lots of doubled faces in there, and it'd be serious work to remove them. I do wonder if there's a utility that could clean up meshes. Certainly netfabb could do it, but that's $$$. MeshLab might be able to do it for you, if you want to try that out. Anyway, it's not a fun bug to fix, but I'll think about it and put it on the [wish list](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#wishlist).

**Comment by erich666** [comment]
Fixed the gaps in version 7.16, https://github.com/erich666/Mineways/releases/tag/v7.16 - thanks! I'll leave this one open, since I could always get inspired to someday really tackle the "this face covers that" problem.

Notes to self: I think the way to do it is, for each face, figure out the one or two rectangles that the face covers (e.g., stairs cover two rectangles). Retrieve the coverage for both faces touching each other. If a face is too complicated to figure out the coverage, just tag it as "no coverage" (though it could get more clever, such as "no me-cover-you, but this much you-cover-me" - not sure that's needed). Given the two coverages, does one fully cover the other? If so, don't output face.

**Comment by erich666** [comment]
Also, I've credited you, @roket333, in the release notes: https://github.com/erich666/Mineways/releases/tag/v7.16

Keep the bugs coming.

**Comment by erich666** [comment]
Closing this one, since it seems to be fixed. Also a little related, I fixed another stairs-related issue, https://github.com/erich666/Mineways/issues/68, in version 8.02.
