### ISSUE TITLE
my level.dat file does not show up when loaded

### ISSUE THREAD

**Issue by TastefullBricodes** [erich666/Mineways#62]
I was trying to load a level.dat file but when it's loaded. it only shows blank

**Comment by erich666** [comment]
If your level.dat files are located in a directory with the path ..."\AppData\Local\Packages\Microsoft.Minecraft"... in it, or have weird directory names like "ZAD1Xfl9AAA=", that's a Bedrock Edition save. You can easily convert worlds from the Bedrock to the Java Edition so that Mineways can read them.

If that is not it, please email me the whole world save directory, I can debug it from here. Contact me [this way](http://www.realtimerendering.com/erich/minecraft/public/mineways/contact.html).

**Comment by TastefullBricodes** [comment]
i use a java edition

**Comment by erich666** [comment]
> i use a java edition

OK, so please email me or otherwise provide me the whole world save directory, I can debug it from here. Contact me [this way](http://www.realtimerendering.com/erich/minecraft/public/mineways/contact.html).

**Comment by erich666** [comment]
Ping, @TastefullBricodes - could you please send on your world, so I can understand your bug? If not, I guess I'll close this one out as "more information needed." Thanks.

**Comment by TastefullBricodes** [comment]
nevermind i just leave this one alone and i abandoned my project
