### ISSUE TITLE
Doesn't work for 1.16

### ISSUE THREAD

**Issue by weathon** [erich666/Mineways#63]
When I output the 1.16-Pre5 world to .obj file and import it into Blender, it tears up.
![image](https://user-images.githubusercontent.com/41298844/85588642-7ceb2400-b608-11ea-896a-bfbf8ba06000.png)

**Comment by erich666** [comment]
Ah, thanks - looks like they changed the data format yet again, in some mysterious way. I'll fix it sometime soon, I hope, if I can figure out what they did.

**Comment by weathon** [comment]
Sorry for disturb, I just realize that it works fine on 1.16.1 release, maybe it just 1.16-Pre5 its own bug?

**Comment by erich666** [comment]
Huh, good to know; thanks for the report. I'll ignore it, then (I don't officially support betas). I couldn't reproduce it here with 1.16.1, so that's good. I did find a bug with exporting coral (that has been there for a long time - I guess no one exports underwater coral). I'll be fixing that soon.
