### ISSUE TITLE
The program crashes if you try to open a world created on the snapshot 21w06a

### ISSUE THREAD

**Issue by LOuroboros** [erich666/Mineways#75]
Title.

I was interested in trying out this software because I heard that Minutor, software that Mineways is a fork of, can inspect items that are currently laying on the floor in the world, but sadly, the program abruptly crashes when I try to open a world created on the latest snapshot.

**Comment by erich666** [comment]
Thanks for reporting this. Yes, Mineways doesn't support beta versions - 1.17 is not released yet. I don't try to add blocks from unreleased versions, as it often costs me a fair bit of extra time doing this sort of work twice, when the release comes out.

However, I do try to avoid having Mineways crash when it runs into new, unknown data. So, I'll take a look this weekend.

**Comment by erich666** [comment]
[Mineways 8.03](https://github.com/erich666/Mineways/releases/tag/v8.03) now does not crash with newer 1.17 snapshots. Minecraft in 1.17 will have a height range of -64 to 319 - it was 0 to 255. The negative heights crashed the Mineways reader.

For snapshot 20w49a and newer, 64 is added to the world's height, so that the now-deeper underworld is handled. This means Mineways Y coordinates for these worlds is displayed incorrectly, until I come up with a full patch. As important, "only" 256 levels, Y=-64 to Y=192, for beta worlds will be displayed. Anything higher is ignored.

**Comment by erich666** [comment]
8.05 now properly shows the full range for 1.17 beta worlds, adjusting the slider to match.
