### ISSUE TITLE
reversion

### ISSUE THREAD

**Issue by StarDream521** [erich666/Mineways#76]
Hello author
Is there a way to convert the converted obj into an archive again? Or schematic?

**Comment by erich666** [comment]
No, there's not. I've actually thought about this idea, just as a puzzle. But, there's really no need normally, so I haven't bothered. 

Also, there's not really identifying information in the OBJ file, which stores only the surface details of the model. That is, imagine you export a big hill. What Mineways outputs is the surface of the hill: the grass and stone and gravel blocks. It ignores all blocks that are surrounded on six sides by other full blocks. So, you likely could never get a full reconstruction from an OBJ file, the internals.

If all blocks were visible by at least one face, then it might be possible. A pain, but possible. But, since you're the first person to ask for such a thing in the past decade, there's not much interest in it.

Note that you can use utilities such as [binvox](https://www.patrickmin.com/minecraft/) to give you the _shape_ of an OBJ model, in schematic form. It won't identify block types, but will at least give you which voxels are covered.
