### ISSUE TITLE
More efficiently create triangles 

### ISSUE THREAD

**Issue by louist103** [erich666/Mineways#77]
Currently each block has triangles exported for it even if there is a flat surface of blocks. This isn't much of an issue for modern systems but for lower performance systems this could cause an issue as well as increase file size.

**Comment by erich666** [comment]
Thanks, and I've thought about it, but pretty much ruled out this idea. It's a lot of work, would only work for one texture export mode, and good DCC programs have similar functionality to remove extraneous triangles already, if a person cares. I just wrote up a longer explanation and put it in the newly-formed "[Nightmare List](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#nightmarelist)" (vs. the "[Wish List](http://www.realtimerendering.com/erich/minecraft/public/mineways/mineways.html#wishlist)" above it).

**Comment by erich666** [comment]
I might as well paste that item here, come to think of it, and close this issue.

Consolidate flat areas of the mesh: large flat grassy areas are common in Minecraft worlds, as are large bodies of water. These could be merged into one giant polygon (for OBJ, with the assumption there's a good triangulator on the other end) or a better mesh that doesn't include all the interior vertices. There are two reasons that make me leery of this one, however. First, it won't work on the mosaiced single-tile texture output that Mineways uses by default, so it will only be useful for when exporting separate textures for every block face. For the giant single-texture mosaics used by default, the texture won't repeat on a simplified triangle mesh. Second, there's a question of whether to remove vertices along the edges of such areas. This will cause T-vertices, where the side of the block has a vertex but there's no vertex on the top of the block. This can lead to cracking artifacts when rendering. But, if you can remove the vertex on the side, too, then that's further savings. Basically, this problem can get pretty complex and tricky if you try to do a good job. Since it's only useful for the "separate texture" export mode, not the default for Mineways, this seems like a lot of work. Most DCC apps already have such functionality anyway, e.g., see [this for Blender](https://blender.stackexchange.com/questions/31467/how-to-reduce-vertex-count-on-a-mesh). So, pass.
