### ISSUE TITLE
Bug when uploading files to Sketchfab

### ISSUE THREAD

**Issue by Tarcadia** [erich666/Mineways#90]
There being a bug report when undergoing the sketchfab uploading process. The failure seems to happen before uploading process but after the model generating. The report says
![图片](https://user-images.githubusercontent.com/47021599/135325269-b9da1a50-f056-4ce6-9141-f04461acb2b7.png)

The failure may caused from a invalied filename. My tracking shows there being a fail when converting the generated model's filename to filepath in skfbPData (Mineways.cpp, line:4093).
![图片](https://user-images.githubusercontent.com/47021599/135325855-ff57fbef-dd91-491c-8cb5-5a89fad61c63.png)

This may caused by Non-Ascii characters in path of %temp%.

**Comment by erich666** [comment]
Thanks, interesting.

Could you provide the wcZip name and full path you were using? I am guessing there are some non-English (not type "char") characters in the path that are perhaps messing up Sketchfab's code here - looks like "filepath" doesn't get set.

You might try running Mineways from a directory such as "c:\temp" to avoid such characters. That said, I tried to reproduce the problem by putting Mineways.exe in a directory with an accented character in the name - it still worked fine with Sketchfab, so I don't know. Which is why any more information you can provide would be a help.

 I'll mention it to Sketchfab (this is their code), though I'm not sure what they can do about it. They should likely be using wchar_t's for their APIs; maybe they do by this point.

**Comment by Tarcadia** [comment]
Dear,


Yes, the path name includes non-ascii chars ("C:\Users\许可\AppData\Local\Temp\Mineways2Skfb.obj.zip"). Acturally it is the user's name which was set at convenience. And Windows allows that. Unfortunately, it cannot be changed easily, unless I create a new user.
The temp path to the file is also not configurable as the path comes from the GetTempPath (Mineways.cpp, line: 3994), which is a rename of API GetTempPathW. And, it returns a wchar format, and then a non-ascii problem comes.
Maybe a safer way to convert strings in wchar to std::string is able to fix that. There seems being a new converter methods introduced in C11.


Regards,
XU KE.





---Original---
From: "Eric ***@***.***&gt;
Date: Thu, Sep 30, 2021 04:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [erich666/Mineways] Bug when uploading files to Sketchfab (#90)




 
Thanks, interesting.
 
Could you provide the wcZip name and full path you were using? I am guessing there are some non-English (not type "char") characters in the path that are perhaps messing up Sketchfab's code here - looks like "filepath" doesn't get set.
 
You might try running Mineways from a directory such as "c:\temp" to avoid such characters. That said, I tried to reproduce the problem by putting Mineways.exe in a directory with an accented character in the name - it still worked fine with Sketchfab, so I don't know. Which is why any more information you can provide would be a help.
 
I'll mention it to Sketchfab (this is their code), though I'm not sure what they can do about it. They should likely be using wchar_t's for their APIs; maybe they do by this point.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by erich666** [comment]
Thanks for the confirmation. I am definitely a beginner when it comes to wchar, etc., so any advice is appreciated. All this code is in the part of the code that Sketchfab themselves graciously contributed. I will contact them and ask whether they might have a fix. Currently their uploader->upload function in Mineways takes strings, not wstrings.

**Comment by erich666** [comment]
I _think_ I have a fix for this problem:

```
    // Set filepath to skfb data
    if (errCode < MW_BEGIN_ERRORS) {
        char filepath[MAX_PATH_AND_FILE * 2];
        size_t retSize;
        wcstombs_s(&retSize, filepath, MAX_PATH_AND_FILE*2, wcZip, MAX_PATH_AND_FILE*2-1);
        assert(retSize > 0);
        skfbPData->skfbFilePath = filepath;
    }
```

Like the [documents say](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/wcstombs-s-wcstombs-s-l), The wcstombs_s function converts a string of wide characters pointed to by wcstr into multibyte characters stored in the buffer pointed to by mbstr.

However, this may not work, because it also says the method terminates when "A wide character that cannot be converted is encountered".

Can you try this little code fix on your end, @Tarcadia ? Or I can make a beta for you to download and try out, but you seem to know how to debug the code, so I'm hoping you can just try it out directly.

**Comment by erich666** [comment]
Full fix is here: https://github.com/erich666/Mineways/commit/a62d646d32bc0480176f1b150aa106e8518178f4 - I hope it works. It should still be better than "%ls", I hope, and will also warn the user that there's a problem and what corrective action to take.

Another possible fix: is there some temporary directory path we can use that does not include the user name? The problem is that the path is currently C:\Users\<wchar user name>\AppData\Local\Temp\Mineways2Skfb.obj.zip for the zip file.

**Comment by Tarcadia** [comment]
I have checked that.
Unfortunately, the _wcstombs_s_ dose not work properly.

The retSize is 0, and the filepath is "", or to say, sometimes it is ['\0', ':', '\\', '\\', ...] that is converted properly untill it run into the chars outof ASCII. It is said in doc that it may cause by encountering a wide character it cannot convert to a multibyte character.

I have checked the charset used in Win, that is still ANSI, it shares codes under different locale. I think it is required to set the locale to the locale of the system.

A fix for that, as what I have found (I am not sure whether it would cause sth. else), is to use _setlocale(LC_ALL,"")_ to specify the locale to the locale of the system, and _setlocale(LC_ALL,"C")_ can be used to reset it default. This helps _wcstombs_s_  to find the convert those unrecognized chars.

I have tried that, it works, but I am not sure whether it makes any other problems. It should be ok as it is running under a minimized set before and the setted locale is always compatible with the minimized one.

**Comment by Tarcadia** [comment]
![图片](https://user-images.githubusercontent.com/47021599/142034961-b2db6033-a8a6-473c-acf2-a3ce9c4cd9f4.png)

Fixed now with setlocale,  #5504003

**Comment by erich666** [comment]
Thanks for the rapid response, and a better fix! I would have pretty much never figured that out. So this fix, right?

```
        setlocale(LC_ALL, "");
        wcstombs_s(&retSize, filepath, MAX_PATH_AND_FILE*2, wcZip, MAX_PATH_AND_FILE*2-1);
        setlocale(LC_ALL, "C");

```
I've now put that in the Mineways repo, so it'll be fixed next release.

This seems safe enough, as [this documentation says](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170):

> At program startup, the equivalent of the following statement is executed:
> 
> setlocale( LC_ALL, "C" );

So resetting after the call seems OK, it's doing the same thing that the program does on startup.

**Comment by Tarcadia** [comment]
It is fixed and closed. Thank you for your efforts to fix that.
And this is my gratitude for your helping adopting the program to multi-languages.

**Comment by erich666** [comment]
Great, thanks for that final fix - good team effort!
