### ISSUE TITLE
model could not input blender

### ISSUE THREAD

**Issue by fantangCK** [erich666/Mineways#92]
https://developer.blender.org/T95344
I can input the model created by mineway v902.But I can't input the model by v911
the model created by mineway.if it isn't blender problem I think it is mineway

**Comment by fantangCK** [comment]
I tested version 902 to version 908 and found that the problem occurred when mineway first supported version 908 of minecraft version 1.18

**Comment by erich666** [comment]
Thanks for reporting this. Unfortunately, I can't currently reproduce the error on Blender 2.92 or 3.0.1. I exported without changing any options in Mineways to an OBJ file and imported it successfully into Blender, then applied MCPrep to its materials. Looks fine.

So, that means I need more information from you. Could you send me your OBJ, MTL, and texture files for your export? That way I can see exactly what settings you've used and can try to reproduce the problem on my end. You might consider making a very small export that reproduces the problem, e.g., export just a single grass block from Mineways and see if that reads into Blender. Any testing is appreciated! But, not required - if you want to simply attach a zip here of your files, I will hopefully be able to reproduce your problem here. If you can't attach here, email to me at erich@acm.org. Oh, and let me know what version of Blender you are using.

![image](https://user-images.githubusercontent.com/803995/151827744-127af4ad-6ab8-49bf-9e21-bb38f89440c5.png)

**Comment by fantangCK** [comment]
> Thanks for reporting this. Unfortunately, I can't currently reproduce the error on Blender 2.92 or 3.0.1. I exported without changing any options in Mineways to an OBJ file and imported it successfully into Blender, then applied MCPrep to its materials. Looks fine.
> 
> So, that means I need more information from you. Could you send me your OBJ, MTL, and texture files for your export? That way I can see exactly what settings you've used and can try to reproduce the problem on my end. You might consider making a very small export that reproduces the problem, e.g., export just a single grass block from Mineways and see if that reads into Blender. Any testing is appreciated! But, not required - if you want to simply attach a zip here of your files, I will hopefully be able to reproduce your problem here. If you can't attach here, email to me at [erich@acm.org](mailto:erich@acm.org). Oh, and let me know what version of Blender you are using.
> 
> ![image](https://user-images.githubusercontent.com/803995/151827744-127af4ad-6ab8-49bf-9e21-bb38f89440c5.png)
my blender version 3.0.1
this is my model had been send to your emil

**Comment by fantangCK** [comment]
> Thanks for reporting this. Unfortunately, I can't currently reproduce the error on Blender 2.92 or 3.0.1. I exported without changing any options in Mineways to an OBJ file and imported it successfully into Blender, then applied MCPrep to its materials. Looks fine.
> 
> So, that means I need more information from you. Could you send me your OBJ, MTL, and texture files for your export? That way I can see exactly what settings you've used and can try to reproduce the problem on my end. You might consider making a very small export that reproduces the problem, e.g., export just a single grass block from Mineways and see if that reads into Blender. Any testing is appreciated! But, not required - if you want to simply attach a zip here of your files, I will hopefully be able to reproduce your problem here. If you can't attach here, email to me at [erich@acm.org](mailto:erich@acm.org). Oh, and let me know what version of Blender you are using.
> 
> ![image](https://user-images.githubusercontent.com/803995/151827744-127af4ad-6ab8-49bf-9e21-bb38f89440c5.png)

my blender version 3.0.1
and my blender model had been sent to you email.
my email is wy0701@vip.qq.com

**Comment by erich666** [comment]
Thanks for sending on the model. I just read it into Blender 3.0.1 successfully: File -> Import -> OBJ, read in the .obj file, and got the image below. I also applied MCPrep to the model successfully, no problem there.

I'm sorry to say I cannot reproduce whatever error it is you are having on Blender. I guess maybe uninstall and reinstall the latest Blender? I don't have any other ideas. The OBJ file also displays fine in G3D, so seems to be correct. If you figure anything out, please do let me know.

![image](https://user-images.githubusercontent.com/803995/151900865-ea6a469f-d9ea-44ff-9aa7-1ea950f85125.png)

**Comment by erich666** [comment]
Looking more closely at https://developer.blender.org/T95344, I tried googling on "blender enum non-color not found in Linear sRGB" - didn't turn up anything that looks identical to your error (that wasn't listed as fixed already).

**Comment by erich666** [comment]
One other idea: send me an export of the same world from verion 9.07 or earlier, where you say things were working. I can then do a "diff" between the two versions and maybe give you some idea what changed (or you can do a diff of the MTL files, which is where I would guess the problem might be, yourself - I recommend Beyond Compare for comparing files).

**Comment by SirHaxe** [comment]
Are you able to import any other obj files?

**Comment by fantangCK** [comment]
> Are you able to import any other obj files?

yep,model exported by v911 can be import

**Comment by fantangCK** [comment]
> One other idea: send me an export of the same world from verion 9.07 or earlier (but 9.07 is ideal, since you say that export works - I definitely made some changes to material export in 9.04, for example, so want to rule those changes out), where you say things were working. I can then do a "diff" between the two versions and maybe give you some idea what changed (or you can do a diff of the MTL files, which is where I would guess the problem might be, yourself - I recommend Beyond Compare for comparing files).

I just test that delete .mtl file then it just can be imported.I think the problem is occurred at its file

**Comment by erich666** [comment]
Right, I figured it must be the MTL file - I haven't touched the meshes in the OBJ file in a long while.

Thanks for emailing me the before and after model files. The main difference is that the line:
`#map_d model-Alpha.png`

is no longer commented out, i.e., it's now:
`map_d model-Alpha.png`

I tested both models, importing each into Blender 3.0.1, and they both import fine. MCprep works on both models.

The "map_d" lines in the .mtl file are something I added in version 9.04 (not 9.08), to improve the import of materials into Blender. This line makes cutout objects (such as flowers) look better when first imported into Blender. I also uncommented map_d because the program jmc2obj also uses map_d; I figured if they've done it for awhile, it would be OK for Mineways to do it, too. I see from your original report that you get the same problem with that program: "When I input my minecaft save model(by jm2obj), blender reports this".

I'm sorry it is causing you problems. My advice remains that you should consider reinstalling Blender. If that does not solve the problem, you could manually edit the .mtl files that jmc2obj or Mineways produces and change all "map_d" to "# map_d" to comment them out.

Since I cannot reproduce this problem on Blender (older or latest versions), I cannot fix anything. I suspect this is a problem with your installation of Blender, but I will try this test on two other machines with Blender on them, next week, just to be sure.

**Comment by erich666** [comment]
Tested on a different PC, same thing - OBJ imports fine, cutout transparency is properly interpreted with materials with map_d defined. Blender 2.93.5 and 3.0.1 tested. So, keeping this one closed, since I can't reproduce it.
